[timestep]
fixed = true
max = 0.0004
min = 0.0004

[domain]
min = [-1.6098, -2.0]
max = [1.6098, 1.2196]
adjustParticle = true
adjustDomain = true

[emitter2.fluidR]
fillDomain = false
min = [0.05,-0.25]
max = [0.5,0.25]
velocity = [ -2.0, 0.0]
adjust = false
shape = 'sphere'

[emitter2.fluidL]
fillDomain = false
min = [-1.0,-0.5]
max = [-0.0,0.5]
velocity = [ 0.0, 0.0]
adjust = false

[emitter2.fluid]
fillDomain = false
min = [-0.25,-1.99]
max = [0.25,-1.49]
velocity = [ 0.0, 0.0]
adjust = false
shape = 'sphere'

[emitter2.fluidBulk]
fillDomain = false
min = [-2,-2]
max = [-1.5, -1.5]
velocity = [ 0.0, 0.0]
adjust = true

[emitter.damBreak]
fillDomain = false
min = [-1.6098,-2.0]
max = [-0.4098, -1.4]
velocity = [ 0.0, 0.0]
adjust = true

[compute]
device='cuda'

[particle]
radius = 0.00420936456012068

[gravity2]
magnitude = 0

[fluid]
c0 = 97.0443197719475
restDensity = 998

[simulation]
boundaryScheme = 'solid'
verbose = false
densityScheme = 'continuum'
scheme = 'deltaSPH'

[pressure]
fluidPressureTerm = 'deltaSPH'
boundaryPressureTerm = 'PBSPH'
gamma = 7.0

[diffusion]
velocityScheme = 'deltaSPH'
densityScheme = 'deltaSPH'
boundaryDiffusion = 0.001
fluidDiffusion = 0.001
alpha = 0.01
delta = 0.1
kinematic = 0.001

[integration]
scheme = 'RK4'
dt = 0.0001

[shifting]
enabled = false
scheme = 'deltaPlus'

[kernel]
targetNeighbors = 50

[export]
active = false
prefix = 'dambreak'
staticBoundary = true
interval = 1