[timestep]
fixed = true

[domain]
min = [-1, -1]
max = [1, 1]
adjustParticle = false
adjustDomain = false

[dfsph]
minDensitySolverIterations = 2
minDivergenceSolverIterations = 2
maxDensitySolverIterations = 256
maxDivergenceSolverIterations = 8
densityThreshold = 1e-4
divergenceThreshold = 1e-2
divergenceSolver = false
backgroundPressure = false
relaxedJacobiOmega = 0.5

[compute]
device='cuda'

[particle]
nx = 128
# radius = 0.025

[gravity]
magnitude = 0

[fluid]
c0 = 100
restDensity = 998
backgroundPressure = false

[simulation]
boundaryScheme = 'none'
verbose = false
densityScheme = 'continuum'
scheme = 'deltaSPH'
mode = 'generative'

[pressure]
fluidPressureTerm = 'deltaSPH'
boundaryPressureTerm = 'PBSPH'
gamma = 7.0

[diffusion]
velocityScheme = 'deltaSPH'
densityScheme = 'MOG'
boundaryDiffusion = 0.001
fluidDiffusion = 0.000
alpha = 0.001
delta = 0.1
kinematic = 0.0

[integration]
scheme = 'RK4'
dt = 0.001

[export]
active = false
prefix = 'generative'
staticBoundary = true
interval = 1

[shifting]
enabled = true
scheme = 'deltaPlus'

[kernel]
targetNeighbors = 50

[generative]
nd = [0,0]
nb = [64,64]
border = 3
n = 256
res = 2
octaves = 4
lacunarity = 2
persistance = 0.25
seed = 1337
boundaryWidth = 0.25


[periodicBC]
periodicX = true
periodicY = true

# [emitter.fluid]
# fillDomain = true
# velocity = [ 0.0, 0.0]
# adjust = true
