[timestep]
fixed = true
max = 0.001
min = 0.001

[dfsph]
minDensitySolverIterations = 2
minDivergenceSolverIterations = 2
maxDensitySolverIterations = 256
maxDivergenceSolverIterations = 8
densityThreshold = 1e-5
divergenceThreshold = 1e-2
divergenceSolver = true
backgroundPressure = false
relaxedJacobiOmega = 0.5

[domain]
min = [-2, -2]
max = [2, 2]
adjustParticle = true
adjustDomain = true

[periodicBC2]
periodicX = true
periodicY = true

[emitter.fluidR]
fillDomain = false
min = [0.5,-1.5]
max = [1.5,-0.5]
velocity = [ -1.0, 0.0]
adjust = false
shape = 'sphere'

[emitter.fluidL]
fillDomain = false
min = [-1.5,-1.5]
max = [-0.5,-0.5]
velocity = [ 1.0, 0.0]
adjust = false
shape = 'sphere'

[emitter2.fluid]
fillDomain = false
min = [-0.5,-0.5]
max = [0.5,0.5]
velocity = [ 0.0, 0.0]
adjust = false
shape = 'sphere'

[emitter2.fluidBulk]
fillDomain = false
min = [-2,-2]
max = [-1.5, -1.5]
velocity = [ 0.0, 0.0]
adjust = true

[emitter2.damBreak]
fillDomain = false
min = [-2.0,-2.0]
max = [-1.0, -1.0]
velocity = [ 0.0, 0.0]
adjust = true

[compute]
device='cpu'

[particle]
radius = 0.005

[gravity]
pointSource = true
magnitude = 10

[fluid]
c0 = 50
umax = 5

[simulation]
boundaryScheme = 'solid'
verbose = false
densityScheme = 'summation'
scheme = 'dfsph'

[pressure]
fluidPressureTerm = 'deltaSPH'
boundaryPressureTerm = 'PBSPH'
gamma = 7.0

[diffusion]
velocityScheme = 'deltaSPH'
densityScheme = 'MOG'
boundaryDiffusion = 0.01
fluidDiffusion = 0.01
alpha = 0.01
delta = 0.1
kinematic = 0.0

[integration]
scheme = 'RK4'
dt = 0.008

[shifting]
enabled = false
scheme = 'semiImplicitEuler'

[kernel]
targetNeighbors = 50

[export]
active = false
prefix = 'collision'
staticBoundary = true
interval = 1